replicaCount: 40

service:
  type: LoadBalancer

image:
  # repository: my_torchserver
  repository: testaixxx.azurecr.io/my_custom_torchserve
  # Overrides the image tag whose default is the chart appVersion.
  # tag: latest-gpu
  tag: latest-gpu

resources: {}
  # limits:
  #   nvidia.com/gpu.shared: 1
  # requests:
  #   nvidia.com/gpu.shared: 1